// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR4yASpdrFGyrAMkMKNT34WmK6r5-AvYo',
    appId: '1:189588659225:web:5d8599ac7858029a8c5e88',
    messagingSenderId: '189588659225',
    projectId: 'pfms-82336',
    authDomain: 'pfms-82336.firebaseapp.com',
    storageBucket: 'pfms-82336.firebasestorage.app',
    measurementId: 'G-CYPK9QCWEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFNgqFtMXrgCRX27w4eC9HxW3iZYUvsDw',
    appId: '1:189588659225:android:d8d64b30bdd4b2478c5e88',
    messagingSenderId: '189588659225',
    projectId: 'pfms-82336',
    storageBucket: 'pfms-82336.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR4yASpdrFGyrAMkMKNT34WmK6r5-AvYo',
    appId: '1:189588659225:web:aa866e277f7730608c5e88',
    messagingSenderId: '189588659225',
    projectId: 'pfms-82336',
    authDomain: 'pfms-82336.firebaseapp.com',
    storageBucket: 'pfms-82336.firebasestorage.app',
    measurementId: 'G-Q251PZBL9P',
  );
}
